/**
 * Teacher API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Gets or sets PassportView
 */
export interface PassportView { 
    /**
     * Gets or sets FullName
     */
    fullName?: string;
    /**
     * Gets or sets PassportNumber
     */
    passportNumber?: string;
    /**
     * Gets or sets DateOfIssue
     */
    dateOfIssue?: Date;
    /**
     * Gets or sets PlaceOfIssue
     */
    placeOfIssue?: string;
    /**
     * Gets or sets ExpiryDate
     */
    expiryDate?: Date;
    /**
     * Gets or sets IssueCountryId
     */
    issueCountryId?: number;
}
