/**
 * Teacher API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * StaffAttendanceAddView
 */
export interface StaffAttendanceAddView { 
    /**
     * Gets or Sets Id
     */
    id?: string;
    /**
     * Gets or Sets StudentId
     */
    staffId?: string;
}
