import { TestClassSectionView } from './test-class-section-view';

/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Gets or Sets UpdateStudentAdmissonView
 */
export interface TestDataView { 
    /**
     * Gets or Sets TestId
     */
    testId?: string;
    /**
     * Gets or Sets TestTypeId
     */
    testTypeId?: number;
    /**
     * Gets or Sets GradingTermId
     */
    gradeTermId?: number;
    /**
     * Gets or Sets TestName
     */
    testName?: string;
    /**
     * Gets or Sets StartDate
     */
    fromDate?: Date;
    /**
     * Gets or Sets EndDate
     */
    toDate?: Date;
    /**
     * Gets or Sets IsPostCalender
     */
    isPostCalender?: number;
    /**
     * Gets or Sets EventClassSections
     */
    testClassSections?: Array<TestClassSectionView>;
}
