/**
 * Teacher API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * ApplicantEducationDetailsView
 */
export interface ApplicantEducationDetailsView { 
    /**
     * Gets or sets
     */
    qualification?: string;
    /**
     * Gets or sets
     */
    startDate?: Date;
    /**
     * Gets or sets
     */
    endDate?: Date;
    /**
     * Gets or sets
     */
    university?: string;
    /**
     * Gets or sets
     */
    institution?: string;
    /**
     * Gets or sets
     */
    specialization?: string;
    /**
     * Gets or sets
     */
    result?: string;
}
