/**
 * Fee
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { Configuration, BASE_PATH } from 'app/service/grading-service';
import { FeeTypeTrancheView } from 'app/modules/configuration/finance/models/fee-type-tranche-view';
import { CustomHttpUrlEncodingCodec } from 'app/service/base/encoder';
import { FeeTypeTranchesView } from 'app/modules/configuration/finance/models/fee-type-tranches-view';
import { BaseUrlConfig, ModuleConfig, FeeModuleConfig } from 'app/url.config';
import { CommonComponent } from 'app/shared/common/common.component';


@Injectable()
export class FeeTypeTranchesService {

    protected basePath = BaseUrlConfig.BasePath + ModuleConfig.Fee;
    // protected basePath = 'http://localhost:8011';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string,
        @Optional() configuration: Configuration, private commonComponent: CommonComponent) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * method for create feetype tranches based on FeeType Id
     * 
     * @param feeTypeTrancheView 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createFeeTypeTranche(feeTypeTrancheView?: FeeTypeTrancheView, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createFeeTypeTranche(feeTypeTrancheView?: FeeTypeTrancheView, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createFeeTypeTranche(feeTypeTrancheView?: FeeTypeTrancheView, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createFeeTypeTranche(feeTypeTrancheView?: FeeTypeTrancheView, observe: any = 'body', reportProgress: boolean = false): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_CreateFeeTypeTranche,
            feeTypeTrancheView,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete FeeType Tranche, returns validation message
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFeeTypeTranches(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFeeTypeTranches(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFeeTypeTranches(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFeeTypeTranches(id: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteFeeTypeTranches.');
        }

        let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('Id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_DeleteteFeeTypeTranche,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * GetAll fee type tranches based on schoolacademicsessionid
     * 
     * @param feeTypeIds Gets or Sets FeeTypeId
     * @param names Gets or Sets Name
     * @param codes Gets or Sets Code
     * @param descriptions Gets or Sets Description
     * @param sortBy Gets or Sets SortBy
     * @param sortOrder Gets or Sets SortOrder
     * @param pageNumber 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllFeeTypeTranches(feeTypeIds?: Array<string>, names?: Array<string>, codes?: Array<string>,
        descriptions?: Array<string>, sortBy?: string, sortOrder?: 0 | 1 | -1, pageNumber?: number,
        pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAllFeeTypeTranches(feeTypeIds?: Array<string>, names?: Array<string>, codes?: Array<string>,
        descriptions?: Array<string>, sortBy?: string, sortOrder?: 0 | 1 | -1, pageNumber?: number,
        pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAllFeeTypeTranches(feeTypeIds?: Array<string>, names?: Array<string>, codes?: Array<string>,
        descriptions?: Array<string>, sortBy?: string, sortOrder?: 0 | 1 | -1, pageNumber?: number,
        pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAllFeeTypeTranches(feeTypeIds?: Array<string>, names?: Array<string>, codes?: Array<string>,
        descriptions?: Array<string>, sortBy?: string, sortOrder?: 0 | 1 | -1, pageNumber?: number,
        pageSize?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });

        queryParameters = this.commonComponent.setQueryParams(feeTypeIds, 'FeeTypeIds', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(names, 'Names', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(codes, 'Codes', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(descriptions, 'Descriptions', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(sortBy, 'SortBy', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(sortOrder, 'SortOrder', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(pageNumber, 'PageNumber', queryParameters);
        queryParameters = this.commonComponent.setQueryParams(pageSize, 'PageSize', queryParameters);
        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_FeeTypeTranchesDetails,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * method for GetAll Fee Types by SchoolAcademicSessionId
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllFeeTypes(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAllFeeTypes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAllFeeTypes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAllFeeTypes(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_FeeTypes,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * method for Get Fee Types tranche by FeeTypeTranche Id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFeeTypeTrancheById(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getFeeTypeTrancheById(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getFeeTypeTrancheById(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getFeeTypeTrancheById(id: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getFeeTypeTrancheById.');
        }

        let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('Id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_FeeTypeTrancheById,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update FeeTypeTranches based on FeeType Id
     * 
     * @param feeTypeTranchesView 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateFeeTypeTranche(feeTypeTranchesView?: FeeTypeTranchesView, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateFeeTypeTranche(feeTypeTranchesView?: FeeTypeTranchesView, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateFeeTypeTranche(feeTypeTranchesView?: FeeTypeTranchesView, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateFeeTypeTranche(feeTypeTranchesView?: FeeTypeTranchesView, observe: any = 'body', reportProgress: boolean = false): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}` + FeeModuleConfig._FeeTypeTranches_UpdateteFeeTypeTranche,
            feeTypeTranchesView,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
