/**
 * Transport
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * TransportScheduleRoutesUpdateView
 */
export interface TransportScheduleRoutesUpdateView { 
    /**
     * Gets Or Sets
     */
    id?: number;
    /**
     * Gets Or Sets
     */
    transportRouteId?: number;
    /**
     * Gets Or Sets
     */
    vehicleId?: number;
    /**
     * Gets Or Sets
     */
    driverStaffId?: number;
    /**
     * Gets Or Sets
     */
    assistantStaffId?: number;
}
