/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * SearchSectionsViewModel
 */
export interface HolidaysListViewModel { 
    /**
     * Gets or sets ClassId
     */
    classId?: Array<any>;
    /**
     * Gets or sets SectionId
     */
    sectionId?: Array<any>;
    /**
     * Gets or sets FromDate
     */
    fromDate?: any;
    /**
     * Gets or sets ToDate
     */
    toDate?: any;
    /**
     * Gets or sets HolidayReason
     */
    holidayReason?: Array<string>;
    /**
     * Gets or sets IsStaffHoliday
     */
    isStaffHoliday?: Array<any>;
    /**
     * Gets or Sets SortOrder
     */
    sortOrder?: HolidaysListViewModel.SortOrderEnum;
    /**
     * Gets or Sets SortBy
     */
    sortBy?: string;
    pageNumber?: number;
    pageSize?: number;
}
export namespace HolidaysListViewModel {
    export type SortOrderEnum = 0 | 1 | -1;
    export const SortOrderEnum = {
        NUMBER_0: 0 as SortOrderEnum,
        NUMBER_1: 1 as SortOrderEnum,
        NUMBER_MINUS_1: -1 as SortOrderEnum
    };
}
