/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentViewModel } from './attachment-model';


/**
 * SyllabusViewModel
 */
export interface SyllabusViewModel { 
    /**
     * Gets or Sets SchoolBoardId
     */
    schoolBoardId?: number;
    /**
     * Gets or Sets ClassId
     */
    classId?: number;
    /**
     * Gets or Sets CourseId
     */
    courseId?: number;
    /**
     * Gets or Sets Name
     */
    name?: string;
    /**
     * Gets or Sets Code
     */
    code?: string;
    /**
     * Gets or Sets BoardSyllabusId
     */
    boardSyllabusId?: number;
    /**
     * Gets And Sets Attachment
     */
    attachment?: AttachmentViewModel;
}
