/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ClassViewModel {
    /**
     * Gets or Sets Name
     */
    name: string;
    /**
     * Gets or Sets ClassReferenceTypeId
     */
    classReferenceTypeId: string | number;
    /**
     * Gets or sets Code
     */
    code?: string;
    /**
     * Gets or sets Description
     */
    description?: string;
}
