/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Gets or Sets VirtualClassOptionsView
 */
export interface VirtualClassOptionsView { 
    /**
     * Gets or Sets ExternalId
     */
    name?: string;
    /**
     * Gets or sets Comment
     */
    comment?: string;
    /**
     * Gets or sets NuumberOfPartizipants
     */
    numberOfPartizipants?: number;
    /**
     * Gets or sets IsPublic
     */
    isPublic?: boolean;
    /**
     * Gets or sets Aappointment
     */
    appointment?: boolean;
    /**
     * Gets or sets Moderated
     */
    moderated?: boolean;
    /**
     * Gets or sets AudioOnly
     */
    audioOnly?: boolean;
    /**
     * Gets or sets AllowUserQuestions
     */
    allowUserQuestions?: boolean;
    /**
     * Gets or sets AllowRecording
     */
    allowRecording?: boolean;
    /**
     * Gets or sets ChatHidden
     */
    chatHidden?: boolean;
    /**
     * Gets or sets ExternalId
     */
    externalId?: string;
}
