/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VirtualClassOptionsView } from '../models/virtual-class-options-view';
import { VirtualClassUserView } from '../models/virtual-class-user-view';


/**
 * Gets or Sets VirtualRoomHashDataView
 */
export interface VirtualRoomHashDataView { 
    /**
     * Gets or Sets ExternalId
     */
    sourceId?: string;
    /**
     * Gets or Sets ExternalId
     */
    user?: VirtualClassUserView;
    /**
     * Gets or sets ExternalType
     */
    options?: VirtualClassOptionsView;
}
