/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Gets or Sets EventParticipantView
 */
export interface EventParticipantView { 
    /**
     * Gets or Sets StudentId
     */
    studentId?: string;
    /**
     * Gets or Sets EventId
     */
    eventId?: string;
    /**
     * Gets or Sets ClassId
     */
    classId?: number;
    /**
     * Gets or Sets SectionId
     */
    sectionId?: number;
    /**
     * Gets or Sets IsFinalist
     */
    isFinalist?: number;
    /**
     * Gets or Sets IsWinner
     */
    isWinner?: number;
    /**
     * Gets or Sets WinningPosition
     */
    winningPosition?: number;
}
