/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders,
    HttpResponse, HttpParams, HttpEvent
} from '@angular/common/http';

import { Observable } from 'rxjs/Observable';
import { CustomHttpUrlEncodingCodec } from '../../base/encoder';



import { BASE_PATH } from '../../base/variables';
import { Configuration } from '../../base/configuration';
import { BillingDetailsView } from '../../../modules/lshp-admin/models/billing-details-view';
import { BaseUrlConfig, ModuleConfig, BaseModuleConfig } from '../../../url.config';


@Injectable()
export class LicenseSetupService {

    // protected basePath = 'http://localhost:5000';
    protected basePath = BaseUrlConfig.BasePath + ModuleConfig.Base;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    public canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }




    /**
     *
     *
     * @param billingDetailsViewModel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public licenseSetUpPost(billingDetailsViewModel?: BillingDetailsView, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public licenseSetUpPost(billingDetailsViewModel?: BillingDetailsView, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public licenseSetUpPost(billingDetailsViewModel?: BillingDetailsView, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public licenseSetUpPost(billingDetailsViewModel?: BillingDetailsView, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}` + BaseModuleConfig._LicenseSetUp,
            billingDetailsViewModel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param billingDetailsViewModel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public licenseSetUpPut(billingDetailsViewModel?: BillingDetailsView, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public licenseSetUpPut(billingDetailsViewModel?: BillingDetailsView, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public licenseSetUpPut(billingDetailsViewModel?: BillingDetailsView, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public licenseSetUpPut(billingDetailsViewModel?: BillingDetailsView, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}` + BaseModuleConfig._LicenseSetUp,
            billingDetailsViewModel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
    * 
    * 
    * @param authorization access token
    * @param instituteId 
    * @param institueLicenceId 
    * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
    * @param reportProgress flag to report request and response progress.
    */
    public licenseSetUpDueSchoolsGet(instituteId?: string, institueLicenceId?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public licenseSetUpDueSchoolsGet(instituteId?: string, institueLicenceId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public licenseSetUpDueSchoolsGet(instituteId?: string, institueLicenceId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public licenseSetUpDueSchoolsGet(instituteId?: string, institueLicenceId?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
        if (instituteId !== undefined) {
            queryParameters = queryParameters.set('InstituteId', <any>instituteId);
        }
        if (institueLicenceId !== undefined) {
            queryParameters = queryParameters.set('InstitueLicenceId', <any>institueLicenceId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        // let consumes: string[] = [
        // ];

        return this.httpClient.get<any>(`${this.basePath}/LicenseSetUp/DueSchools`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }


}
