/**
 * Course
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * GradingTermCloneViewModel
 */
export interface GradingTermCloneViewModel { 
    /**
     * Gets or sets of ClassId
     */
    classId?: number;
    /**
     * Gets or sets of SectionId
     */
    sectionsId?: Array<any>;
    /**
     * Gets or sets of GradingTermId
     */
    gradingTermId?: string;
}
