/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SchoolAcademicClassSectionView {
    schoolAcademicSessionId?: number | string;
    classId: Array<number | string>;
    sectionId: Array<number | string>;
    classTeacherId?: number | string;
    maxCapacity: number;
    schoolBoardId: number;
    id?: number | string;
}
