/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * This is a UserDashboardPreferencce Type ViewModel
 */
export interface UserDashboardPreferenceView {
    /**
     * Gets or Sets SortOrder
     */
    sortOrder?: number;
    /**
     * Gets or Sets IsVisible
     */
    isVisible?: number;
    id?: string;
}
