/**
 * BaseWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Gets or sets
 */
export interface ClassRequirementView { 
    /**
     * Gets or sets ClassId
     */
    classId: number;
    /**
     * Gets or sets CourseCategoryId
     */
    courseCategoryId: number;
    /**
     * Gets or sets CourseId
     */
    courseId: number;
    /**
     * Gets or sets PassMarks
     */
    passMarks?: number;
    /**
     * Gets or sets SchoolBoardId
     */
    schoolBoardId?: number;
}
